[profile.default]
solc_version = '0.8.28'
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'

remappings = [
  "@/contracts/=contracts/",
]

[fuzz]
runs = 256

[invariant] #invariant section
fail_on_revert = false
runs = 1215
depth = 23